on: 
  push:
    paths:
      - 'example/**'
      - 'metascore/**'
      - 'src/**'
      - 'test/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.8.1
          install-moc: true
          vessel-version: 0.6.2
      - run: ./test/test.sh
